# Creation time : 2m
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - oracle_network
    depends_on:
      ords:
        condition: service_healthy
  oracle:
    image: gvenzl/oracle-free:latest
    hostname: oracle
    environment:
      ORACLE_PASSWORD: ${DATABASE_SYSTEM_PASSWORD}
      APP_USER: ${DATABASE_APP_USER}
      APP_USER_PASSWORD: ${DATABASE_APP_PASSWORD}
    ports:
      - 1521:1521
    volumes:
      - $DB_DATA_BASE_DIR/data/databases:/opt/oracle/oradata
    networks:
      - oracle_network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
  ords:
    image: container-registry.oracle.com/database/ords:latest
    hostname: ords
    environment:
      IGNORE_APEX: "$IGNORE_APEX"
      VIRTUAL_HOST: $ORDS_SETTING_API_URL
      VIRTUAL_PORT: $ORDS_SETTING_API_PORT
    ports:
      - 27017:27017
    volumes:
       - $ORDS_SETTINGS_BASE_DIR/ords_secrets:/opt/oracle/variables
       - $ORDS_SETTINGS_BASE_DIR/ords_settings/:/etc/ords/config/
    networks:
      - oracle_network
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://ords:8181/ords"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      oracle:
        condition: service_healthy
networks:
  oracle_network:
    driver: bridge
