# Creation time : 1m
services:
  oracle_database:
    image: gvenzl/oracle-free:latest
    hostname: oracledb23c
    environment:
      ORACLE_PASSWORD: ${DATABASE_SYSTEM_PASSWORD}
      APP_USER: ${DATABASE_APP_USER}
      APP_USER_PASSWORD: ${DATABASE_APP_PASSWORD}
    ports:
      - 1521:1521
    volumes:
      - $DB_DATA_BASE_DIR/data:/opt/oracle/oradata
    networks:
      - oracle_network
    healthcheck: 
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  oracle_network:
    driver: bridge
