# Creation time : 6m
services:
  twitterfeed:
    image: wvbirder/twitterfeed
    ports:
      - 9080:9080
    networks:
      - oracle_network
  ords:
    image: container-registry.oracle.com/database/ords
    hostname: ords
    environment:
      IGNORE_APEX: "$IGNORE_APEX"
      VIRTUAL_HOST: $ORDS_SETTING_API_URL
      VIRTUAL_PORT: $ORDS_SETTING_API_PORT
    ports:
      - 27017:27017
    volumes:
       - $ORDS_SETTINGS_BASE_DIR/ords_secrets:/opt/oracle/variables
       - $ORDS_SETTINGS_BASE_DIR/ords_settings/:/etc/ords/config/
    networks:
      - oracle_network
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://ords:8181/ords"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  oracle_network:
    name: db23c_database_oracle_network
    external: true


docker run -d -it --rm --name restclient -p=8002:8002 -e ORACLE_USER="app" -e ORACLE_PASSWORD="Imust-change2023It" -e ORACLE_CONNECT='oracle:1521/FREEPDB1' -e DS='oracle' wvbirder/restclient


ORACLE_USER || "alpha",
  password      : process.env.ORACLE_PASSWORD || "Alpha2017_",
  connectString : process.env.ORACLE_CONNECT || "172.17.0.3/orclpdb1.localdomain",
  externalAuth  : process.env.ORACLE_EXTERNALAUTH ?