# Creation time : 6m
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - oracle_network
    depends_on:
      ords:
        condition: service_healthy
  ords:
    image: container-registry.oracle.com/database/ords
    hostname: ords
    environment:
      IGNORE_APEX: "$IGNORE_APEX"
      VIRTUAL_HOST: $ORDS_SETTING_API_URL
      VIRTUAL_PORT: $ORDS_SETTING_API_PORT
    ports:
      - 27017:27017
    volumes:
       - $ORDS_SETTINGS_BASE_DIR/ords_secrets:/opt/oracle/variables
       - $ORDS_SETTINGS_BASE_DIR/ords_settings/:/etc/ords/config/
    networks:
      - oracle_network
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://ords:8181/ords"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  oracle_network:
    name: db23c_database_oracle_network
    external: true
